/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hamba;

/**
 *
 * @author PC 32
 */
public class Pesawat extends javax.swing.JFrame {

    /**
     * Creates new form Pesawat
     */
    public Pesawat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        boxpesawat = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRoute = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        etHarga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        etBeli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        etJumlahH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Radiosejalan = new javax.swing.JRadioButton();
        Radiopp = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        Diskon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TotalHarga = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Radiocash = new javax.swing.JRadioButton();
        Radiokredit = new javax.swing.JRadioButton();
        Potongan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        HargaBayar = new javax.swing.JTextField();
        btnHarga = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("JADWAL PENERBAWANGAN PESAWAT");

        jLabel2.setText("Bandara Internasional Soekarno-Hatta");

        boxpesawat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silahkan Pilih", "GARUDA", "MERPATI", "MANDALA", "LION", "SEMPATI" }));
        boxpesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxpesawatActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Pesawat");

        jLabel4.setText("Route");

        txtRoute.setEnabled(false);

        jLabel5.setText("Harga Tiket");

        etHarga.setEnabled(false);

        jLabel6.setText("Jumlah Dibeli");

        etBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etBeliActionPerformed(evt);
            }
        });

        jLabel7.setText("Jumlah Harga");

        etJumlahH.setEnabled(false);
        etJumlahH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etJumlahHActionPerformed(evt);
            }
        });

        jLabel8.setText("Jenis Perjalanan");

        buttonGroup1.add(Radiosejalan);
        Radiosejalan.setText("Sejalan");
        Radiosejalan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Radiosejalan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiosejalanActionPerformed(evt);
            }
        });

        buttonGroup1.add(Radiopp);
        Radiopp.setText("Pulang - Pergi");
        Radiopp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioppActionPerformed(evt);
            }
        });

        jLabel9.setText("Discount");

        jLabel10.setText("Total Harga Tiket");

        TotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalHargaActionPerformed(evt);
            }
        });

        jLabel11.setText("Potongan Pembayaran");

        jLabel12.setText("Pembayaran");

        buttonGroup2.add(Radiocash);
        Radiocash.setText("Cash");
        Radiocash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadiocashActionPerformed(evt);
            }
        });

        buttonGroup2.add(Radiokredit);
        Radiokredit.setText("Kartu Kredit");

        Potongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PotonganActionPerformed(evt);
            }
        });

        jLabel13.setText("Harga Yang Harus Dibayar");

        btnHarga.setText("JUMLAH HARGA");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });

        btnBayar.setText("HARGA BAYAR");

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setText("KELUAR");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(boxpesawat, 0, 91, Short.MAX_VALUE)
                                    .addComponent(txtRoute)
                                    .addComponent(etHarga)
                                    .addComponent(etBeli)
                                    .addComponent(etJumlahH))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Radiokredit)
                                            .addComponent(Radiocash)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)))
                                    .addComponent(jLabel13))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Potongan)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(HargaBayar)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(Diskon)
                                                    .addComponent(TotalHarga)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(Radiopp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(2, 2, 2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8)
                                                    .addComponent(Radiosejalan))
                                                .addGap(0, 0, Short.MAX_VALUE)))))))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHarga)
                        .addGap(18, 18, 18)
                        .addComponent(btnBayar)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnKeluar)))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(boxpesawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Radiosejalan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Radiopp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etJumlahH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Diskon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TotalHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Radiocash)
                    .addComponent(Potongan, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radiokredit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(HargaBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHarga)
                    .addComponent(btnBayar)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etJumlahHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etJumlahHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etJumlahHActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        String jumlah = etBeli.getText();
        int jumlah = jumlah;
        int harga = etHarga.getText();
        int total harga = jumlah * harga;
        etJumlahH.setText(total);
    }//GEN-LAST:event_btnHargaActionPerformed

    private void boxpesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxpesawatActionPerformed
        if (boxpesawat.getSelectedItem()=="Silahkan Pilih"){
            txtRoute.setText("");
            etHarga.setText("");
        } else if(boxpesawat.getSelectedItem()=="GARUDA"){
            txtRoute.setText("JKT - BALI");
            etHarga.setText("Rp 1.000.000");
        }else if(boxpesawat.getSelectedItem()=="MERPATI"){
            txtRoute.setText("JKT - LOMBOK");
            etHarga.setText("Rp 800.000");
        }else if(boxpesawat.getSelectedItem()=="MANDALA"){
            txtRoute.setText("JKT - JATIM");
            etHarga.setText("Rp 700.000");
        }else if(boxpesawat.getSelectedItem()=="LION"){
            txtRoute.setText("JKT - MEDAN");
            etHarga.setText("Rp 500.000");
        }else if(boxpesawat.getSelectedItem()=="SEMPATI"){
            txtRoute.setText("JKT - RIAU");
            etHarga.setText("Rp 850.000");
        }
    }//GEN-LAST:event_boxpesawatActionPerformed

    private void etBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etBeliActionPerformed
        
    }//GEN-LAST:event_etBeliActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        etBeli.setText("");
        etJumlahH.setText("");
        Diskon.setText("");
        TotalHarga.setText("");
        Potongan.setText("");
        HargaBayar.setText("");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void TotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalHargaActionPerformed

    private void PotonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PotonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PotonganActionPerformed

    private void RadiosejalanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadiosejalanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadiosejalanActionPerformed

    private void RadioppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioppActionPerformed

    private void RadiocashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadiocashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadiocashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesawat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesawat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Diskon;
    private javax.swing.JTextField HargaBayar;
    private javax.swing.JTextField Potongan;
    private javax.swing.JRadioButton Radiocash;
    private javax.swing.JRadioButton Radiokredit;
    private javax.swing.JRadioButton Radiopp;
    private javax.swing.JRadioButton Radiosejalan;
    private javax.swing.JTextField TotalHarga;
    private javax.swing.JComboBox<String> boxpesawat;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField etBeli;
    private javax.swing.JTextField etHarga;
    private javax.swing.JTextField etJumlahH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtRoute;
    // End of variables declaration//GEN-END:variables
}
